### PR TITLE
More links

### PR DESCRIPTION
**Pull request by mattias-p**
More link fixing. Using standard autolinks simplifies automatic link checking.

### CODE REVIEW

**Comment by mattias-p** [comment]
The purpose is to increase the range of automatic link checking to include autolinks. Standard Commonmark parser libraries are able to extract standard autolinks but not [GFM autolinks](https://github.github.com/gfm/#autolinks-extension-). Those libraries are used by link checking tools.

I occasionally use tools to look for broken links. That's how I found the broken links in #518. Unfortunately the tool I used didn't know about the GFM autolink extension, so I there were lots of links that didn't get checked that time around. Among them the two links to <http://www.zonecheck.fr/features.shtml> that are fixed in this PR.

To mitigate the problem of overlooked links for the future I searched for GFM autolinks in zonemaster and added angle brackets to all the links I could find.

I agree that an item about this should be added to the style guide.

**Comment by matsduf** [comment]
I want to see a more complete proposal of how links should be written Zonemaster documentation before this PR is merged. When I test, putting "<...>" around a link does not add anything. It does not change the parsing.

**Comment by mattias-p** [comment]
This is not about presentation on Github. Github renders Commonmark autolinks and GFM autolinks identically.
This is about using tools to go over all the links in an entire repository to verify that they all still work properly. Since GFM autolinks is an extension to Commonmark, they are unlikely to be recognized by Commonmark parsing libraries, and this is why I missed lots of links when I believed I'd checked them all.

**Comment by matsduf** [comment]
According to <http://spec.commonmark.org/0.28/#autolinks> the following three should result in autolinks but only the first does in Github:

1. <http://foo.bar.baz>
2. <a+b+c:d>
3. <localhost:5001/foo>

Am I doing something wrong?

**Comment by mattias-p** [comment]
Looks like you've discovered two Github bugs.

They're autolinks according to GFM as well:
* <https://github.github.com/gfm/#example-582>
* <https://github.github.com/gfm/#example-585>

And for reference: <https://github.github.com/gfm/#what-is-github-flavored-markdown->

**Comment by sandoche2k** [comment]
Except for the confusion of the links <..>, i am ok with the content

**Comment by sandoche2k** [comment]
@mattias-p then pls. merge

**Comment by sandoche2k** [comment]
@mattias-p please close

**Comment by mattias-p** [comment]
@sandoche2k This is already merged.

**Pull request merged**
