### PR TITLE
Added nameserver08 for 0X20 test

### PR DESCRIPTION
**Pull request by sandoche2k**
@pawal please verify and integrate.

### CODE REVIEW

**Comment by pawal** [comment]
The test case identifier is very very long. Could you make it shortern?

Perhaps, "qname case preservation in answers from authoritative name server"

**Comment by sandoche2k** [comment]
I have done it. But i have not used the same wording as yours, since the
verficiation here is done only at the question section

**Comment by pawal** [comment]
I have read through the details in the "ordered description" now, but I fail to see where you verify that the qname matches the _answer_ which is the whole point of the test. It is useless to compare the qmane with the qname?  I think you just forgot to mention the DNS reply with the ANSWER and QUESTION sections.

**Comment by sandoche2k** [comment]
Yes, i have not been precise to mention the response packet.

I have updated wherein the comparison is done between the QNAME in the
question section in the query with the QNAME in the question section in the
response.

I did test with some well known authoritative servers, wherein the answer
section of the response does not preserve the case. And, after discussion
with Stephane, i restricted to question section of the response.

**Comment by sandoche2k** [comment]
@vlevigneron test spec completed

**Comment by vlevigneron** [comment]
Implementation is completed but:

1/ Specifications have changed and are incomplete now (no idea why).
2/ I guess you mean Method4 and Method5 instead of Method2 and Method3
3/ Can you provide list of authoritative servers with the "bad" behaviour. Of general way, when you know of relevant examples, please provide them. This facilitates the implementation of unit tests.

**Comment by sandoche2k** [comment]
Thanks Vincent. Fixed the incomplete specification.

No, i did mean "Method 2" and "Method 3".  The idea is to get the name
servers and query them with the mixed case FQDN. Correct me if i am wrong.

The examples i found in the literature have been fixed. If i have new
examples, i will update.

Sandoche.

**Comment by vlevigneron** [comment]
Calle and I answered several times about the use of Method2...5, Method2
and Method3 return names while Method4 and Method5 return name server
objects you can query. So in this case, if we want to query them, it's
method4 and method5.

le 15 juin, sandoche2k a ?crit :
> Thanks Vincent. Fixed the incomplete specification.
> 
> No, i did mean "Method 2" and "Method 3".  The idea is to get the name
> servers and query them with the mixed case FQDN. Correct me if i am wrong.
> 
> The examples i found in the literature have been fixed. If i have new
> examples, i will update.
> 
> Sandoche.
> 
> On 12 June 2015 at 08:28, vlevigneron <notifications@github.com> wrote:
> 
> > Implementation is completed but:
> >
> > 1/ Specifications have changed and are incomplete now (no idea why).
> > 2/ I guess you mean Method4 and Method5 instead of Method2 and Method3
> > 3/ Can you provide list of authoritative servers with the "bad" behaviour.
> > Of general way, when you know of relevant examples, please provide them.
> > This facilitates the implementation of unit tests.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/dotse/zonemaster/pull/388#issuecomment-111377600>.
> >
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dotse/zonemaster/pull/388#issuecomment-112309466

-- 
	Vincent Levigneron  A.F.N.I.C.  Vincent.Levigneron@nic.fr

**Pull request merged**
