### PR TITLE
Add missing documentation from public tree in SUMMARY.md

### PR DESCRIPTION
**Pull request by tgreenx**
## Purpose

This PR updates the file SUMMARY.md (used for Mdbook documentation generation) with missing files from the public tree.

## How to test this PR

N/A. Or double check that any other important public documentation file is not missing.

### CODE REVIEW

**Review by marc-vanderwal — DISMISSED** [review]

**Comment by matsduf** [comment]
We need to have script support for the update of SUMMARY.md to make it possible to update it at release time. It would be OK if manual update is required if there is a script that collects the data for the update. At release time we have the following step where this update could be included: 

https://github.com/zonemaster/zonemaster/blob/master/docs/internal/maintenance/ReleaseProcess-release.md#13-generate-documents

**Review by matsduf — APPROVED** [review]

**Review by marc-vanderwal — APPROVED** [review]

**Comment by matsduf** [comment]
There are more documents that should be linked from https://github.com/zonemaster/zonemaster/blob/af155aed1297e8d60ef5d7034e999d812ff37c45/docs/public/specifications/tests/README.md but that is probably outside the scope of this PR.

**Review by matsduf — APPROVED** [review]

**Comment by matsduf** [comment]
There are three test cases listed under test zones in SUMMARY.md but there should be seven.

**Review by matsduf — APPROVED** [review]

**Comment by matsduf** [comment]
The following seems to be a simple tool to look for missing links (but will not find broken links). And you @tgreenx seem to have found all of the missing ones.
```
public % for file in $(find . -name "*.md" | perl -p -e 's!^./!!'); do if ! egrep -q $file SUMMARY.md; then echo $file; fi; done
SUMMARY.md
configuration/global-cache.md
specifications/test-zones/Consistency-TP/README.md
specifications/test-zones/Consistency-TP/consistency05.md
specifications/test-zones/Consistency-TP/consistency06.md
specifications/test-zones/DNSSEC-TP/dnssec03.md
specifications/test-zones/Nameserver-TP/nameserver15.md
specifications/tests/ArgumentsForTestCaseMessages.md
specifications/tests/ImplementedTestCases.md
upgrading/backend/upgrade_zonemaster_backend_ver_11.1.0.md
```

**Comment by matsduf** [comment]
No, specifications/tests/ImplementedTestCases.md is missing.

**Comment by matsduf** [comment]
> > No, specifications/tests/ImplementedTestCases.md is missing.
> 
> From my understanding it was originally left out intentionally to simplify the documentation. For this file there is no risk of broken link as there is only one reference to this document in the `doc/public` tree, found in [specifications/tests/README.md](https://github.com/zonemaster/zonemaster/blob/v2023.2.1/docs/public/specifications/tests/README.md). And this file is not included in the the structure of the public documentation book, defined in [SUMMARY.md](https://github.com/zonemaster/zonemaster/blob/v2023.2.1/docs/public/SUMMARY.md).

I do not understand the reasoning behind leaving it out, but I find a broken link in here: https://doc.zonemaster.fr/v2023.2.1/specifications/tests/index.html

**Review by mattias-p — APPROVED** [review]

**Comment by matsduf** [comment]
Was merged into releases/v2023.2.2 branch for v2023.2.2 release, which was never released.

**Pull request merged**
