### PR TITLE
Discussions: Proposal of merging Config and Policy into Profile

### PR DESCRIPTION
**Pull request by matsduf**
This PR is for discussions only and is not meant to be merged.

### CODE REVIEW

**Comment by matsduf** [comment]
@vlevigneron, @sandoche2k, @mtoma and @mattias-p! Have you been able to review my proposal? All comments are welcome. Please add the comments directly in the web so that we can easily follow the threads.

**Comment by matsduf** [comment]
With alternative 1 I think it is possible to limit code changes to Zonemaster/Config.pm, with alternative 2 there are more modules to be updated.

**Comment by mattias-p** [comment]
After F2F discussions the project group has agreed on solution Alternative 2 as presented in this PR.

**Comment by sandoche2k** [comment]
@matsduf this is a proposal just for discussion or do you want it to be merged as a document.
@vlevigneron as the vote is for alternative2 and from your last mail, it seems you are working on it already. Isn't it?

**Comment by vlevigneron** [comment]
le 22 nov., sandoche2k a ?crit :
> @matsduf this is a proposal just for discussion or do you want it to be merged as a document.
> @vlevigneron as the vote is for alternative2 and from your last mail, it seems you are working on it already. Isn't it? 
> 
Yes, I'll do my best to have it done for our next meeting.

> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/dotse/zonemaster/pull/499#issuecomment-346287321

-- 
	Vincent Levigneron  A.F.N.I.C.  Vincent.Levigneron@nic.fr

**Comment by sandoche2k** [comment]
@matsduf For reference : https://github.com/sandoche2k/zonemaster/blob/add-config-feature-file/docs/internal-documentation/maintenance/ConfigurableFeatures.md

**Comment by sandoche2k** [comment]
@matsduf will be compiling the documentation in "design" directory

**Comment by matsduf** [comment]
See #541

**Pull request closed without merging**
