### PR TITLE
Fix issue 140

### PR DESCRIPTION
**Pull request by sandoche2k**
Updated delegation02.md based on the comment by Mats

### CODE REVIEW

**Comment by matsduf** [comment]
@sandoche2k, this PR contains more than you want. You should create your branch as a copy of the develop branch that is even with dotse/zonemaster:develop.

**Comment by sandoche2k** [comment]
> You should create your branch as a copy of the develop branch that is even with dotse/zonemaster:develop

@matsduf I think i have done that. Did i go wrong somewhere?

**Comment by matsduf** [comment]
In your PR there are 7 commits. The first four are not related. The next two are merge commits. The last one is the relevant one.

Description|Commit ID
-----------|----------
Added a file for our internal use |1339800
Formatted the added file 		|	83fafc5
Updated the configurable features file 		|	0120051
Corrected issue in Markdown heading: Contract or Bug reporting		|	9be1636
Merge remote-tracking branch 'upstream/develop' into develop 		|	d49f760
Merge remote-tracking branch 'upstream/master' into develop 		|	d2ca5d0
Updated delegation02.md based on the comment by Mats for the pull request #482 |9aaa70d 

Checkout the develop branch and make it even with the Zonemaster repo, and then add your update to that. And create the PR.

**Comment by matsduf** [comment]
@sandoche2k, I suggest that you close this PR and open a new PR based on a fresh clone of the develop branch.

**Pull request closed without merging**
