### PR TITLE
Update ReleaseProcess.md

### PR DESCRIPTION
**Pull request by matsduf**
Corrected minor error in command plus some clarification of the text.

### CODE REVIEW

**Comment by matsduf** [comment]
@sandoche2k, can you review?

**Comment by sandoche2k** [comment]
Yes, i will take a look.

**Comment by sandoche2k** [comment]
https://github.com/dotse/zonemaster/pull/486

**Comment by sandoche2k** [comment]
I am not able to view the first half of the file. Hence i am sending you
the changes one by one.

Make sure the prerequisites section in [README.md](
https://github.com/dotse/zonemaster/blob/master/README.md)
 -is up to date with regard to [
https://github.com/dotse/zonemaster/blob/master/docs/internal-documentation/maintenance/SupportCriteria.md
].
 +is up to date with regard to [Support
 +Criteria](
https://github.com/dotse/zonemaster/blob/master/docs/internal-documentation/maintenance/SupportCriteria.md
).
~

**Comment by sandoche2k** [comment]
* zonemaster-engine - [MANIFEST](
https://github.com/dotse/zonemaster-engine/blob/master/MANIFEST) (make
manifest)
 + * zonemaster-engine - [MANIFEST](
https://github.com/dotse/zonemaster-engine/blob/master/MANIFEST)

And create the manifest file for the engine :
https://github.com/dotse/zonemaster-engine/issues/256

**Comment by matsduf** [comment]
The MANIFEST file for zonemaster-engine is created by "make manifest" step documented. Updated to reflect that.

**Comment by matsduf** [comment]
@sandoche2k, your suggestion has been included. Please review the result.

**Pull request merged**
