### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by JohanIIS**
Fixed image link and adjusted text for syntax.

### CODE REVIEW

**Comment by JohanIIS** [comment]
I agree that it might seem pointless to have a folder and README for one single file, and I think I prefer the idea of moving it up one level instead of renaming it.

**Comment by mattias-p** [comment]
If the file is moved up one level, should it also be renamed "Requirements.md" to preserve the directory structure?

**Comment by matsduf** [comment]
@sandoche2k, what do you say about my proposal?

**Comment by sandoche2k** [comment]
@JohanIIS Can you merge the PR?

**Pull request merged**
