### PR TITLE
Fix issue #513

### PR DESCRIPTION
**Pull request by sandoche2k**

### CODE REVIEW

**Comment by matsduf** [comment]
@sandoche2k, can you please give a short description of this PR. It seems to cover more than issue #513. Does it resolve everything in #513?

**Comment by mattias-p** [comment]
AFAICT it solves all but one remaining item from #513.
[docs/internal-documentation/requirements/README.md](https://github.com/dotse/zonemaster/blob/develop/docs/internal-documentation/requirements/README.md) still has a broken image link.

**Comment by sandoche2k** [comment]
The link for the image seems to be the same as others. But, it is broken ?

**Comment by mattias-p** [comment]
Yes it is broken. Does the image show up for you? It shouldn't because the `requirements` directory doesn't have a `docs` subdirectory. The best fix would probably be to replace the current heading with plain text one simply saying "Internal Documentation".

**Comment by matsduf** [comment]
@sandoche2k, it does not look like this PR solves everything what is stated in #513, and it does other things (removing file instead of fixing markdown), but I approve what it does.

I think all PRs should have a short description of what it does, and if it refers to an issue, there should be a link to that issue in the description.

**Pull request merged**
